version: '3.4'
services:
 app:
  build: .
  ports:
   - "3000:3000"
  env_file: .env
  depends_on:
   - db
  volumes:
   - .:/home/api/app
  entrypoint: ["npm","start"]
 data_server:
  build: .
  ports:
   - "5000:5000"
  env_file: .env
  depends_on:
   - db
  volumes:
   - .:/home/api/app
  entrypoint: ["npm","run", "data"]
 db:
  image: mongo:latest
  ports:
   - "27017:27017"
  env_file: .env